cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    test:
      email: test
      name: test
      password: $2b$12$OsJqRHUXZJ.QuhOJEXRiGO.CDW41ivfJoF.axcmCU3tcb0ebp26JC